# Generated by Django 4.0.1 on 2022-01-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course_instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='course_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='course_instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='previousyearquestion',
            name='course_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='previousyearquestion',
            name='course_instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
