import { useAuth } from "../contexts/auth";
import useSWR, { mutate } from 'swr'
import { api } from "../utils/api";
import { useMemo, useState } from "react";
import { useTable } from 'react-table'
import Head from 'next/head'
import { AddNoteModal } from '../components/Notes/AddNoteModal'
import { BsPlus } from "react-icons/bs";
import { AddPYQModal } from "../components/PYQs/AddPYQModal";

export default function PYQs() {
    //? states
    const [showAddPYQModal, setShowAddPYQModal] = useState(false)

    const { user, loading }: any = useAuth();
    // const { data: { data: pages } = {}, isValidating } = useSWR(loading ? false : '/pages', api.get)
    const data = useMemo(
        () => [
            {
                sno: 1,
                name: 'Sem 1',
                url: 'https://www.google.com/',
                batch: 'Third Year'
            },
            {
                sno: 2,
                name: 'Sem 2',
                url: 'https://www.google.com/',
                batch: 'Third Year'
            },
            {
                sno: 3,
                name: 'Sem 3',
                url: 'https://www.google.com/',
                batch: 'Third Year'
            },
            {
                sno: 4,
                name: 'Sem 4',
                url: 'https://www.google.com/',
                batch: 'Third Year'
            },
            {
                sno: 5,
                name: 'Sem 5',
                url: 'https://www.google.com/',
                batch: 'Third Year'
            },
        ],
        []
    )

    const columns = useMemo(
        () => [
            {
                Header: 'S.No.',
                accessor: 'sno', // accessor is the "key" in the data
            },
            {
                Header: 'Name',
                accessor: 'name',
            },
            {
                Header: 'URL',
                accessor: 'url',
            },
            {
                Header: 'Batch',
                accessor: 'batch',
            },
        ],
        []
    )

    const tableInstance = useTable({ columns, data })
    const {
        getTableProps,
        getTableBodyProps,
        headerGroups,
        rows,
        prepareRow,
    } = tableInstance


    return (
        <div className="w-full bg-bg-primary flex flex-col">
            <AddPYQModal showAddPYQModal={showAddPYQModal} setShowAddPYQModal={setShowAddPYQModal} />
            <Head>
                <title>Notes</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="grid grid-cols-5 gap-0 justify-center py-48 px-14 space-y-8">
                <div
                    className="col-span-5 flex flex-row items-center justify-between">
                    <h3 className="font-bold text-4xl">PYQs</h3>
                    <button onClick={() => setShowAddPYQModal(true)} type="button" className="flex items-center space-x-2 p-2 duration-200 transition-all rounded-md shadow-md hover:shadow-xl bg-primary text-white font-semibold">
                        <BsPlus className="h-9 w-9" />
                        <span className="text-lg">
                            Add PYQ
                        </span>
                    </button>
                </div>
                <table className="col-span-5" {...getTableProps()}>
                    <thead>
                        {// Loop over the header rows
                            headerGroups.map((headerGroup, index) => (
                                // Apply the header row props
                                <tr className="" {...headerGroup.getHeaderGroupProps()}>
                                    {// Loop over the headers in each row
                                        headerGroup.headers.map(column => (
                                            // Apply the header cell props
                                            <th className="bg-primary border-primary border-2 text-white p-4" {...column.getHeaderProps()}>
                                                {// Render the header
                                                    column.render('Header')}
                                            </th>
                                        ))}
                                </tr>
                            ))}
                    </thead>
                    <tbody {...getTableBodyProps()}>
                        {// Loop over the table rows
                            rows.map(row => {
                                // Prepare the row for display
                                prepareRow(row)
                                return (
                                    // Apply the row props
                                    <tr className="" {...row.getRowProps()}>
                                        {// Loop over the rows cells
                                            row.cells.map(cell => {
                                                // Apply the cell props
                                                return (
                                                    <td className="text-center p-3 border-2 border-gray-800" {...cell.getCellProps()}>
                                                        {// Render the cell contents
                                                            cell.render('Cell')}
                                                    </td>
                                                )
                                            })}
                                    </tr>
                                )
                            })}
                    </tbody>
                </table>
            </div>
        </div>
    )
}