# Generated by Django 3.2 on 2021-12-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_todo_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Feedback',
        ),
    ]
