# Generated by Django 3.2 on 2021-12-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_todo_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('name', models.CharField(default='', max_length=100)),
                ('course_id', models.CharField(default='', max_length=10)),
                ('batch', models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2020)),
                ('course_instructor', models.CharField(default='', max_length=100)),
                ('gdrive_link', models.URLField(default='', max_length=500)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousYearQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('name', models.CharField(default='', max_length=100)),
                ('course_id', models.CharField(default='', max_length=10)),
                ('batch', models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default='')),
                ('course_instructor', models.CharField(default='', max_length=100)),
                ('gdrive_link', models.URLField(default='', max_length=500)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
