# Generated by Django 3.2 on 2021-12-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211231_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-vote_score']},
        ),
    ]
